version: '3'
services:
  flashsale:
    build: .
    ports:
      - "50051:50051"
    links:
      - mysql:mysql
      - redis:redis
  mysql:
    image: mysql:latest
    restart: always
    networks:
      - dev
    ports:
      - "50052:50052"
    environment:
      MYSQL_ROOT_PASSWORD: 'Xx941320'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'Xx941320'
      MYSQL_DATABASE: 'flashsale'
    restart:
      always
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
networks:
 dev:
  driver: bridge
volumes:
 redis_data:
 mysql_data: