version: '3'
services:
  flashsale:
    build: .
    ports:
     - "5000:5000"
    links:
      - mysql:mysql
      - redis:redis
  mysql:
    image: "centos/mysql-57-centos7"
    restart: always
    networks:
      - dev
    ports:
      - "50052:50052"
    environment:
      MYSQL_USER: 'ronxu'
      MYSQL_PASSWORD: 'Xx941320'
      MYSQL_DATABASE: 'flashsale'
    restart:
      always
  redis:
    image: "centos/redis-32-centos7"
    ports:
      - "6379:6379"
networks:
 dev:
  driver: bridge
volumes:
 redis_data:
 mysql_data: