// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flashsale.proto
#ifndef GRPC_flashsale_2eproto__INCLUDED
#define GRPC_flashsale_2eproto__INCLUDED

#include "flashsale.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace flashsale {

class FlashsaleService final {
 public:
  static constexpr char const* service_full_name() {
    return "flashsale.FlashsaleService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::flashsale::FlashsaleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>> Asyncflashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>>(AsyncflashsaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>> PrepareAsyncflashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>>(PrepareAsyncflashsaleRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>* AsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::flashsale::FlashsaleResponse>* PrepareAsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::flashsale::FlashsaleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>> Asyncflashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>>(AsyncflashsaleRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>> PrepareAsyncflashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>>(PrepareAsyncflashsaleRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>* AsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>* PrepareAsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_flashsale_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_flashsale() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestflashsale(::grpc::ServerContext* context, ::flashsale::FlashsaleRequest* request, ::grpc::ServerAsyncResponseWriter< ::flashsale::FlashsaleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_flashsale<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_flashsale() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::flashsale::FlashsaleRequest, ::flashsale::FlashsaleResponse>(
          [this](::grpc::ServerContext* context,
                 const ::flashsale::FlashsaleRequest* request,
                 ::flashsale::FlashsaleResponse* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->flashsale(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_flashsale<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_flashsale() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_flashsale() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestflashsale(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_flashsale() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->flashsale(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void flashsale(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_flashsale : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_flashsale() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::flashsale::FlashsaleRequest, ::flashsale::FlashsaleResponse>(std::bind(&WithStreamedUnaryMethod_flashsale<BaseClass>::Streamedflashsale, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_flashsale() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedflashsale(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::flashsale::FlashsaleRequest,::flashsale::FlashsaleResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_flashsale<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_flashsale<Service > StreamedService;
};

}  // namespace flashsale


#endif  // GRPC_flashsale_2eproto__INCLUDED
