// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: flashsale.proto

#include "flashsale.pb.h"
#include "flashsale.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace flashsale {

static const char* FlashsaleService_method_names[] = {
  "/flashsale.FlashsaleService/flashsale",
};

std::unique_ptr< FlashsaleService::Stub> FlashsaleService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FlashsaleService::Stub> stub(new FlashsaleService::Stub(channel));
  return stub;
}

FlashsaleService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_flashsale_(FlashsaleService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FlashsaleService::Stub::flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::flashsale::FlashsaleResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_flashsale_, context, request, response);
}

void FlashsaleService::Stub::experimental_async::flashsale(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_flashsale_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>* FlashsaleService::Stub::AsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::flashsale::FlashsaleResponse>::Create(channel_.get(), cq, rpcmethod_flashsale_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::flashsale::FlashsaleResponse>* FlashsaleService::Stub::PrepareAsyncflashsaleRaw(::grpc::ClientContext* context, const ::flashsale::FlashsaleRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::flashsale::FlashsaleResponse>::Create(channel_.get(), cq, rpcmethod_flashsale_, context, request, false);
}

FlashsaleService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FlashsaleService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FlashsaleService::Service, ::flashsale::FlashsaleRequest, ::flashsale::FlashsaleResponse>(
          std::mem_fn(&FlashsaleService::Service::flashsale), this)));
}

FlashsaleService::Service::~Service() {
}

::grpc::Status FlashsaleService::Service::flashsale(::grpc::ServerContext* context, const ::flashsale::FlashsaleRequest* request, ::flashsale::FlashsaleResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace flashsale

