// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: flashsale.proto

#include "flashsale.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace flashsale {
class FlashsaleRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FlashsaleRequest>
      _instance;
} _FlashsaleRequest_default_instance_;
class FlashsaleResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<FlashsaleResponse>
      _instance;
} _FlashsaleResponse_default_instance_;
}  // namespace flashsale
namespace protobuf_flashsale_2eproto {
static void InitDefaultsFlashsaleRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::flashsale::_FlashsaleRequest_default_instance_;
    new (ptr) ::flashsale::FlashsaleRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::flashsale::FlashsaleRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FlashsaleRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFlashsaleRequest}, {}};

static void InitDefaultsFlashsaleResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::flashsale::_FlashsaleResponse_default_instance_;
    new (ptr) ::flashsale::FlashsaleResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::flashsale::FlashsaleResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_FlashsaleResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFlashsaleResponse}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_FlashsaleRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_FlashsaleResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::flashsale::FlashsaleRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::flashsale::FlashsaleRequest, usrname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::flashsale::FlashsaleRequest, usrkey_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::flashsale::FlashsaleResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::flashsale::FlashsaleResponse, result_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::flashsale::FlashsaleRequest)},
  { 7, -1, sizeof(::flashsale::FlashsaleResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::flashsale::_FlashsaleRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::flashsale::_FlashsaleResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "flashsale.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017flashsale.proto\022\tflashsale\"3\n\020Flashsal"
      "eRequest\022\017\n\007usrname\030\001 \001(\t\022\016\n\006usrkey\030\002 \001("
      "\t\"#\n\021FlashsaleResponse\022\016\n\006result\030\001 \001(\t2Z"
      "\n\020FlashsaleService\022F\n\tflashsale\022\033.flashs"
      "ale.FlashsaleRequest\032\034.flashsale.Flashsa"
      "leResponseb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 218);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "flashsale.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_flashsale_2eproto
namespace flashsale {

// ===================================================================

void FlashsaleRequest::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlashsaleRequest::kUsrnameFieldNumber;
const int FlashsaleRequest::kUsrkeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlashsaleRequest::FlashsaleRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_flashsale_2eproto::scc_info_FlashsaleRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:flashsale.FlashsaleRequest)
}
FlashsaleRequest::FlashsaleRequest(const FlashsaleRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  usrname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.usrname().size() > 0) {
    usrname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usrname_);
  }
  usrkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.usrkey().size() > 0) {
    usrkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usrkey_);
  }
  // @@protoc_insertion_point(copy_constructor:flashsale.FlashsaleRequest)
}

void FlashsaleRequest::SharedCtor() {
  usrname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usrkey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FlashsaleRequest::~FlashsaleRequest() {
  // @@protoc_insertion_point(destructor:flashsale.FlashsaleRequest)
  SharedDtor();
}

void FlashsaleRequest::SharedDtor() {
  usrname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usrkey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FlashsaleRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FlashsaleRequest::descriptor() {
  ::protobuf_flashsale_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_flashsale_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlashsaleRequest& FlashsaleRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_flashsale_2eproto::scc_info_FlashsaleRequest.base);
  return *internal_default_instance();
}


void FlashsaleRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:flashsale.FlashsaleRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  usrname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  usrkey_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool FlashsaleRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:flashsale.FlashsaleRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string usrname = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usrname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usrname().data(), static_cast<int>(this->usrname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "flashsale.FlashsaleRequest.usrname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string usrkey = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_usrkey()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->usrkey().data(), static_cast<int>(this->usrkey().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "flashsale.FlashsaleRequest.usrkey"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:flashsale.FlashsaleRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:flashsale.FlashsaleRequest)
  return false;
#undef DO_
}

void FlashsaleRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:flashsale.FlashsaleRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string usrname = 1;
  if (this->usrname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usrname().data(), static_cast<int>(this->usrname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleRequest.usrname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->usrname(), output);
  }

  // string usrkey = 2;
  if (this->usrkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usrkey().data(), static_cast<int>(this->usrkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleRequest.usrkey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->usrkey(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:flashsale.FlashsaleRequest)
}

::google::protobuf::uint8* FlashsaleRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:flashsale.FlashsaleRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string usrname = 1;
  if (this->usrname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usrname().data(), static_cast<int>(this->usrname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleRequest.usrname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->usrname(), target);
  }

  // string usrkey = 2;
  if (this->usrkey().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->usrkey().data(), static_cast<int>(this->usrkey().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleRequest.usrkey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->usrkey(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flashsale.FlashsaleRequest)
  return target;
}

size_t FlashsaleRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flashsale.FlashsaleRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string usrname = 1;
  if (this->usrname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usrname());
  }

  // string usrkey = 2;
  if (this->usrkey().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->usrkey());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FlashsaleRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:flashsale.FlashsaleRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const FlashsaleRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlashsaleRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:flashsale.FlashsaleRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:flashsale.FlashsaleRequest)
    MergeFrom(*source);
  }
}

void FlashsaleRequest::MergeFrom(const FlashsaleRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flashsale.FlashsaleRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.usrname().size() > 0) {

    usrname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usrname_);
  }
  if (from.usrkey().size() > 0) {

    usrkey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.usrkey_);
  }
}

void FlashsaleRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:flashsale.FlashsaleRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlashsaleRequest::CopyFrom(const FlashsaleRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashsale.FlashsaleRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlashsaleRequest::IsInitialized() const {
  return true;
}

void FlashsaleRequest::Swap(FlashsaleRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlashsaleRequest::InternalSwap(FlashsaleRequest* other) {
  using std::swap;
  usrname_.Swap(&other->usrname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  usrkey_.Swap(&other->usrkey_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FlashsaleRequest::GetMetadata() const {
  protobuf_flashsale_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_flashsale_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void FlashsaleResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int FlashsaleResponse::kResultFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

FlashsaleResponse::FlashsaleResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_flashsale_2eproto::scc_info_FlashsaleResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:flashsale.FlashsaleResponse)
}
FlashsaleResponse::FlashsaleResponse(const FlashsaleResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.result().size() > 0) {
    result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.result_);
  }
  // @@protoc_insertion_point(copy_constructor:flashsale.FlashsaleResponse)
}

void FlashsaleResponse::SharedCtor() {
  result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

FlashsaleResponse::~FlashsaleResponse() {
  // @@protoc_insertion_point(destructor:flashsale.FlashsaleResponse)
  SharedDtor();
}

void FlashsaleResponse::SharedDtor() {
  result_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void FlashsaleResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* FlashsaleResponse::descriptor() {
  ::protobuf_flashsale_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_flashsale_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const FlashsaleResponse& FlashsaleResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_flashsale_2eproto::scc_info_FlashsaleResponse.base);
  return *internal_default_instance();
}


void FlashsaleResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:flashsale.FlashsaleResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool FlashsaleResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:flashsale.FlashsaleResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string result = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_result()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->result().data(), static_cast<int>(this->result().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "flashsale.FlashsaleResponse.result"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:flashsale.FlashsaleResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:flashsale.FlashsaleResponse)
  return false;
#undef DO_
}

void FlashsaleResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:flashsale.FlashsaleResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string result = 1;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), static_cast<int>(this->result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleResponse.result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->result(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:flashsale.FlashsaleResponse)
}

::google::protobuf::uint8* FlashsaleResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:flashsale.FlashsaleResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string result = 1;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), static_cast<int>(this->result().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "flashsale.FlashsaleResponse.result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->result(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:flashsale.FlashsaleResponse)
  return target;
}

size_t FlashsaleResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:flashsale.FlashsaleResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string result = 1;
  if (this->result().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->result());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void FlashsaleResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:flashsale.FlashsaleResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const FlashsaleResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const FlashsaleResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:flashsale.FlashsaleResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:flashsale.FlashsaleResponse)
    MergeFrom(*source);
  }
}

void FlashsaleResponse::MergeFrom(const FlashsaleResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:flashsale.FlashsaleResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.result().size() > 0) {

    result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.result_);
  }
}

void FlashsaleResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:flashsale.FlashsaleResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void FlashsaleResponse::CopyFrom(const FlashsaleResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:flashsale.FlashsaleResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool FlashsaleResponse::IsInitialized() const {
  return true;
}

void FlashsaleResponse::Swap(FlashsaleResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void FlashsaleResponse::InternalSwap(FlashsaleResponse* other) {
  using std::swap;
  result_.Swap(&other->result_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata FlashsaleResponse::GetMetadata() const {
  protobuf_flashsale_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_flashsale_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace flashsale
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::flashsale::FlashsaleRequest* Arena::CreateMaybeMessage< ::flashsale::FlashsaleRequest >(Arena* arena) {
  return Arena::CreateInternal< ::flashsale::FlashsaleRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::flashsale::FlashsaleResponse* Arena::CreateMaybeMessage< ::flashsale::FlashsaleResponse >(Arena* arena) {
  return Arena::CreateInternal< ::flashsale::FlashsaleResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
